// Fund Clicker: Theme Vibes
// Pre-designed aesthetic packages that orgs can choose from.
// Each vibe defines colors, typography feel, and visual personality.
// Orgs pick a vibe during onboarding, then customize from there.

export const VIBES = [
  {
    id: "retro-arcade",
    name: "Retro Arcade",
    description: "Pixel art nostalgia. Neon glow. 8-bit energy.",
    preview: "The original Jared Clicker feel",
    colors: {
      primary: "#FFD700",
      secondary: "#1a1a2e",
      accent: "#e94560",
      surface: "#16213e",
      text: "#ffffff",
      textMuted: "#8888aa",
      success: "#4ade80",
      danger: "#ef4444",
    },
    borderRadius: 8,
    fontWeight: "bold",
    personality: "playful",
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    description: "Clean lines. Soft gradients. Sophisticated simplicity.",
    preview: "For professional, polished fundraisers",
    colors: {
      primary: "#6366f1",
      secondary: "#0f172a",
      accent: "#f59e0b",
      surface: "#1e293b",
      text: "#f1f5f9",
      textMuted: "#94a3b8",
      success: "#22c55e",
      danger: "#ef4444",
    },
    borderRadius: 16,
    fontWeight: "medium",
    personality: "refined",
  },
  {
    id: "nature-earth",
    name: "Nature & Earth",
    description: "Warm tones. Organic textures. Grounded and inviting.",
    preview: "For community and outdoor groups",
    colors: {
      primary: "#d97706",
      secondary: "#1c1917",
      accent: "#65a30d",
      surface: "#292524",
      text: "#fafaf9",
      textMuted: "#a8a29e",
      success: "#16a34a",
      danger: "#dc2626",
    },
    borderRadius: 12,
    fontWeight: "medium",
    personality: "warm",
  },
  {
    id: "neon-cyber",
    name: "Neon Cyber",
    description: "Electric colors. Dark vibes. Futuristic edge.",
    preview: "For youth groups and tech-savvy orgs",
    colors: {
      primary: "#06b6d4",
      secondary: "#020617",
      accent: "#f43f5e",
      surface: "#0f172a",
      text: "#e2e8f0",
      textMuted: "#64748b",
      success: "#10b981",
      danger: "#f43f5e",
    },
    borderRadius: 6,
    fontWeight: "bold",
    personality: "edgy",
  },
  {
    id: "pastel-pop",
    name: "Pastel Pop",
    description: "Soft pastels. Bubbly shapes. Joyful and light.",
    preview: "For kids' ministries and family events",
    colors: {
      primary: "#c084fc",
      secondary: "#faf5ff",
      accent: "#fb923c",
      surface: "#f3e8ff",
      text: "#1e1b4b",
      textMuted: "#7c3aed",
      success: "#34d399",
      danger: "#fb7185",
    },
    borderRadius: 20,
    fontWeight: "medium",
    personality: "playful",
  },
  {
    id: "classic-gold",
    name: "Classic Gold",
    description: "Rich golds. Deep navy. Timeless elegance.",
    preview: "For traditional churches and formal events",
    colors: {
      primary: "#ca8a04",
      secondary: "#0c1222",
      accent: "#b91c1c",
      surface: "#1a2332",
      text: "#fefce8",
      textMuted: "#a3a3a3",
      success: "#15803d",
      danger: "#b91c1c",
    },
    borderRadius: 4,
    fontWeight: "bold",
    personality: "refined",
  },
];

export function getVibe(id) {
  return VIBES.find(v => v.id === id) || VIBES[0];
}
